# Define a imagem base do Node.js
FROM node:18-alpine

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia os arquivos de dependência primeiro para otimizar o cache
COPY package*.json ./

# Instala as dependências da API
RUN npm install

# Copia o resto do código da sua API para dentro do contêiner
COPY . .

 # Informa ao Docker que a aplicação usa a porta 3000
EXPOSE 3000

# Comando padrão para iniciar a API quando o contêiner rodar
CMD [ "npm", "start" ]